# Generated by Django 5.2.3 on 2025-07-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='genre',
            new_name='genres',
        ),
    ]
